name: Networks healthcheck

on: pull_request

  # schedule:
  #   - cron: '0 0/4 * * *'


env:
  ACALA_PROD_AUTH_TOKEN: 'token'
  ACALA_TEST_AUTH_TOKEN: 'token'
  MOONBEAM_PROD_AUTH_TOKEN: 'token'
  MOONBEAM_TEST_AUTH_TOKEN: 'token'
  MOONPAY_PRODUCTION_SECRET: 'token'
  MOONPAY_TEST_SECRET: 'token'

  CI_KEYSTORE_PASS: 'token'
  CI_KEYSTORE_KEY_ALIAS: 'token'
  CI_KEYSTORE_KEY_PASS: 'token'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          repository: nova-wallet/nova-wallet-android
          ref: 'fix/network_test'
          token: ${{ secrets.PAT }}

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21d

      - name: Rename NDK 21 folder to NDK 23
        run: |
          rm -rf /Users/runner/Library/Android/sdk/ndk/23.1.7779620
          mv /Users/runner/Library/Android/sdk/ndk/21.4.7075529 /Users/runner/Library/Android/sdk/ndk/23.1.7779620

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Add permissions
        run: chmod +x .github/workflows/networks_test.sh

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          disable-animations: true
          profile: Nexus 5X
          api-level: 28
          script: .github/workflows/networks_test.sh

      - name: Rerun tests
        if: ${{ failure() }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          disable-animations: true
          profile: Nexus 5X
          api-level: 28
          script: .github/workflows/networks_test.sh

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: report
          path: ./allure-results.tar

  report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: report
          path: ./

      - name: Unzip results
        run: tar -xvf allure-results.tar

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Debug
        run: |
          ls -R

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 30

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

  alert:
    runs-on: ubuntu-latest
    needs: report
    if: always() && (needs.test.result == 'failure')
    steps:
      - name: Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Network tests failed, lets check:

            https://nova-wallet.github.io/test-runner/${{github.run_number}}
